# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hocky's Diary
email: hocky.yudhiono@gmail.com
description: You can read a guy's perspective of his life
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: hockyy
github_username: hockyy
gems:
  - jemoji
# Build settings
markdown: kramdown
